### ISSUE TITLE
Context Menu - Enable/Disable Clickthrough

### ISSUE THREAD

**Issue by metal-face** [overlayeddev/overlayed#1]
Using tauri, add an item to the operating system's context menu to enable clickthrough.

**Comment by Hacksore** [comment]
looks like it's not officially supported but there seems to be a plugin.

https://github.com/tauri-apps/tauri/issues/4338

**Comment by metal-face** [comment]
right on, I'll check this out

**Comment by metal-face** [comment]
@Hacksore so yeah, [the plugin ](https://lib.rs/crates/tauri-plugin-context-menu) looks promising, and then based on what I saw in these [docs](https://tauri.app/v1/guides/features/command), we can call your methods in main from the client?

![image](https://github.com/Hacksore/overlayed/assets/101987676/ed515ef6-b572-45b4-a2b0-1fbcd30ce4c4)

**Comment by Hacksore** [comment]
we'll get em next time boyz
