### ISSUE TITLE
First time user experience

### ISSUE THREAD

**Issue by Hacksore** [overlayeddev/overlayed#13]
Found some rough edges so when you first onboard to Overlayed:

- it should not be hidden from the macOS dock / windows taskbar as it makes the app hard to find if you have to do something else
- it should not be force pinned on top as it can obscure the CTA in discord

**Comment by cored0wn** [comment]
Hey man, just stumbled across your post in the official discord forum.
Directly checked out your project and it looks great! Just as a quick feedback: think about to implement maybe some tooltips for the buttons in the header. I've no idea what the arrows will do for example.

Keep up that good work and if i can assist you with anything let me know.

**Comment by Hacksore** [comment]
You can at least tab to overlayed now but will consider solving the pinning issue later on.
