### ISSUE TITLE
Blank GUI screen on Arch Hyprland

### ISSUE THREAD

**Issue by schembriaiden** [overlayeddev/overlayed#134]
**Describe the bug**

**To Reproduce**
1. Install using AppImageLauncher on Hyprland
2. After installing it open thew Application and you just have a blank GUI

**Expected behavior**
Just have a blank GUI

**Screenshots**
![image](https://github.com/overlayeddev/overlayed/assets/81376423/7b95f5b3-0fe1-4c4a-a648-fa1a9810523b)

**Desktop (please complete the following information):**
To be clear I am using Vesktop

![image](https://github.com/overlayeddev/overlayed/assets/81376423/6650a78b-0a0b-44f7-9979-8439234f09ba)

**Additional context**

**Comment by Hacksore** [comment]
Vesktop is currently not supported please see https://github.com/overlayeddev/overlayed/issues/78 which 

More info on this comment about the technical reasons. https://github.com/overlayeddev/overlayed/issues/78#issuecomment-2131357800

**Comment by schembriaiden** [comment]
Apologies I missed it, thanks for the quick support
