### ISSUE TITLE
macOS installer not showing drag and drop installation

### ISSUE THREAD

**Issue by Hacksore** [overlayeddev/overlayed#14]
Right now I have two options either

- Upgrade to tauri 2.x as it has support via https://github.com/tauri-apps/tauri/pull/7964
- Wait for the backport to 1.x via https://github.com/tauri-apps/tauri/pull/8334

**Comment by DannyAziz** [comment]
Ever figure a way around this?

**Comment by Hacksore** [comment]
@DannyAziz I think the best option for now is to wait for tauri to be stable on 2.x, it's at least [beta right now](https://beta.tauri.app/blog/tauri-2-0-0-beta/).

Then I just get it for free when I upgrade. Not sure if they will solve https://github.com/tauri-apps/tauri/pull/8334 so a 1.x solution is probably unlikely.

Are you facing a similar issue in a tauri project?

**Comment by Hacksore** [comment]
Going to close this for now and possibly reinvestigate once I move to tauri 2.x
