### ISSUE TITLE
Canary shows crash reporter when CMD+Q

### ISSUE THREAD

**Issue by Hacksore** [overlayeddev/overlayed#152]
With the new `NSPanel` changes (#149) canary will crash when you open it and cmd+q.

Repro
1. [run canary build](https://overlayed.dev/canary)
1. open "Overlayed Canary"
1. press `cmd+q`
1. app will show crash reporter

Video demo:

https://github.com/overlayeddev/overlayed/assets/996134/e4ae4eef-20a9-47da-8701-eb0ac495ad86

Stack dump:
https://gist.github.com/Hacksore/a3cf26b3b9b31e0de41f631bde0dcfc5

**Comment by Hacksore** [comment]
This is 100% associated with the https://github.com/tauri-apps/tauri-plugin-window-state.

What I've observered is that if you have a `~/Library/Application Support/com.overlayed.canary.dev/.window-state` file and you `CMD+Q` the crash reporter will show.

**Comment by Hacksore** [comment]
@ahkohd Just FYI I was able to reproduce this on another system and you can see https://github.com/overlayeddev/overlayed/issues/152#issuecomment-2212636523 to understand what I've experienced.

**Comment by ahkohd** [comment]
So will you report this?
