### ISSUE TITLE
OS-aware Download Card

### ISSUE THREAD

**Issue by Pyr33x** [overlayeddev/overlayed#163]
Only render specific download card base on viewer OS, this can get done using [react-device-detect](https://www.npmjs.com/package/react-device-detect)
I think this is a better way instead of having three different download cards for each platform 

![Downloads](https://github.com/user-attachments/assets/fb34ac3c-4187-4b9b-ab21-7c071ee301aa)

**Comment by Hacksore** [comment]
that is totally inspired by https://spacedrive.com 😂

but yeah this is helpful, I also probably should not hotlink the downloads right from `github.com` and instead have the api vend them.

something like how discord does it via:
```
https://discord.com/api/download?platform=<platform>
```

**Comment by Pyr33x** [comment]
yea that is, exactly.

**Comment by MUK-Dev** [comment]
Hi, is this up for grabs?

**Comment by Hacksore** [comment]
@MUK-Dev it’s all yours now 😉

**Comment by MUK-Dev** [comment]
😅 Ok, I'll take a look

**Comment by MUK-Dev** [comment]
The project is not really working for me.
I tried the setup guide in the Local.md but it just fails

```
> turbo start "--filter=desktop"

• Packages in scope: desktop
• Running start in 1 packages
• Remote caching disabled
┌ desktop#start > cache bypass, force executing 7d44694d57155bf0
│
│ > desktop@0.0.0 start G:\Web Development\overlayed\apps\desktop
│ > tauri dev
│
│      Running BeforeDevCommand (`pnpm dev`)
│
│ > desktop@0.0.0 dev G:\Web Development\overlayed\apps\desktop
│ > vite
│
│ [sentry-vite-plugin] Warning: No auth token provided. Will not create release. Please set the `authToken
│ ` option. You ca
│ n find information on how to generate a Sentry auth token here: https://docs.sentry.io/api/auth/
│ [sentry-vite-plugin] Warning: No auth token provided. Will not upload source maps. Please set the `authT
│ oken` option. Yo
│ u can find information on how to generate a Sentry auth token here: https://docs.sentry.io/api/auth/
│ [sentry-vite-plugin] Info: Sending error and performance telemetry data to Sentry. To disable telemetry,
│  set `options.te
│ lemetry` to `false`.
│   ➜  Local:   http://localhost:1420/
│   ➜  Network: use --host to expose
│         Info Watching G:\Web Development\overlayed\apps\desktop\src-tauri for changes...
│    Compiling webview2-com-sys v0.19.0
│    Compiling overlayed v0.0.0 (G:\Web Development\overlayed\apps\desktop\src-tauri)
│ error: failed to run custom build command for `overlayed v0.0.0 (G:\Web Development\overlayed\apps\deskt
│ op\src-tauri)`
│
│ Caused by:
│   process didn't exit successfully: `G:\Web Development\overlayed\apps\desktop\src-tauri\target\debug\bu
│ ild\overlayed-60
│ a3ca28d1d94633\build-script-build` (exit code: 101)
│   --- stdout
│   cargo:rerun-if-env-changed=TAURI_CONFIG
│   cargo:rerun-if-changed=tauri.conf.json
│   cargo:rustc-cfg=desktop
│   cargo:rustc-cfg=dev
│   package.metadata does not exist
│
│   --- stderr
│   thread 'main' panicked at C:\Users\z tech\.cargo\registry\src\index.crates.io-6f17d22bba15001f\embed-r
│ esource-2.4.2\sr
│ c\windows_not_msvc.rs:49:23:
│   Couldn't to execute windres to compile "G:\Web Development\overlayed\apps\desktop\src-tauri\target\deb
│ ug\build\overlay
│ ed-a3c326c1dd2904e8\out\resource.rc" into "G:\Web Development\overlayed\apps\desktop\src-tauri\target\de
│ bug\build\overla
│ yed-a3c326c1dd2904e8\out/libresource.a": program not found
│   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
│ warning: build failed, waiting for other jobs to finish...
│  ELIFECYCLE  Command failed with exit code 101.
│
│ command finished with error: command (G:\Web Development\overlayed\apps\desktop) C:\Users\z tech\AppData
│ \Local\pnpm\pnpm.exe run start exited (101)
└────>
 ERROR  run failed: command  exited (101)
 ELIFECYCLE  Command failed with exit code 101.
```

**Comment by Hacksore** [comment]
Yeah running the `api` and `web` was not well documented, pushed https://github.com/overlayeddev/overlayed/commit/d1fd68937f34eceb4f6ca2180687583fe04af3ac that allows you to run `pnpm start:mocked` in the `app/web` dir.

Let me know if that works!

**Comment by Hacksore** [comment]
Just saw you were on windows so pushed a fix for setting the env.

**Comment by MUK-Dev** [comment]
Ok, I will try

**Comment by MUK-Dev** [comment]
Can you tell me a little about setting up wrangler.
```
Error: You need to register a workers.dev subdomain before running the dev command in remote mod
You can either enable local mode by pressing l, or register a workers.dev subdomain 
```

**Comment by Hacksore** [comment]
@MUK-Dev you don't need to worry about wrangler.
```
cd apps\web
pnpm start:mocked
```

Then it should proxy the requests to static json files located here `apps\web\public\mocks\*.json`.

edit: Make sure your branch is updated with `main` though.

**Comment by MUK-Dev** [comment]
Ok

**Comment by MUK-Dev** [comment]
You can check out the preview in the pull request.

**Comment by Hacksore** [comment]
@Pyr33x / @MUK-Dev I think there will have to be a bit of collaboration here for #188 and #191 (hard to review and maintain two PRs) 

@Pyr33x I really don't want to remove the cool star button here that I yoinked from @picklenik
<img width="662" alt="image" src="https://github.com/user-attachments/assets/10acbad4-4296-46a8-b6b9-7543cefdb28d">

I do like the design on https://obsidian.md
<img width="961" alt="image" src="https://github.com/user-attachments/assets/2a2a753a-ca2c-4367-a488-f8dbd90137b9">

**Comment by Pyr33x** [comment]
> @Pyr33x I really don't want to remove the cool star button here that I yoinked from @PickleNik
> I do like the design on https://obsidian.md

It's okay, imma be pushing new changes soon 👀

**Comment by MUK-Dev** [comment]
So, what are you guys thinking of doing here?

**Comment by Hacksore** [comment]
let me get around to reviewing these PRs sometime next week.

**Comment by Hacksore** [comment]
Going to close both #191 and #188 since there are some rough edges in the PRs. They are def in the right direction but we need allow all the versions to be downloaded.

As a perquisite we need to first add a page like this that will list all the platform downloads.

https://obsidian.md/download

**Comment by Hacksore** [comment]
Closing for now but we can revisit later.
