### ISSUE TITLE
OS-aware Download Card Rendering

### ISSUE THREAD

**Issue by Pyr33x** [overlayeddev/overlayed#164]
Only render specific download card base on viewer OS, this can get done using [react-device-detect](https://www.npmjs.com/package/react-device-detect)
I think this is a better way instead of having three different download cards for each platform 

![Downloads](https://github.com/user-attachments/assets/fb34ac3c-4187-4b9b-ab21-7c071ee301aa)

**Comment by Hacksore** [comment]
Closed as duplicate in favor of #163
