### ISSUE TITLE
AI integration (you know it needs to happen)

### ISSUE THREAD

**Issue by niemal** [overlayeddev/overlayed#165]
**Is your feature request related to a problem? Please describe.**
It is not related to an existing problem. It is about creating one.

**Describe the solution you'd like**
I would like to have AI integrated which will do something. Here's some ideas that we can do:
- Log people's conversations in a transcript.
- ~~Make them sound like an entirely different person. Hook speech to make them sound more aggressive or friendlier.~~
  - Actually that's not possible :'(. Unless?
  
**Describe alternatives you've considered**
No alternatives, this is raw startup potential.

**Additional context**
Wait, is this even possible within our context?

**Comment by Hacksore** [comment]
Im pinning this to collect moar downvotes

**Comment by niemal** [comment]
@Kampouse You are late to the party. cc @maxdemaio

**Comment by Hacksore** [comment]
# 🎧 $\textsf{\color[rgb]{0.0, 0, 1.0}H\color[rgb]{0.0, 0, 1.0}E\color[rgb]{0.1, 0, 0.9}A\color[rgb]{0.1, 0, 0.9}D\color[rgb]{0.2, 0, 0.8}P\color[rgb]{0.2, 0, 0.8}H\color[rgb]{0.2, 0, 0.8}O\color[rgb]{0.3, 0, 0.7}N\color[rgb]{0.3, 0, 0.7}E\color[rgb]{0.4, 0, 0.6}S\color[rgb]{0.4, 0, 0.6} \color[rgb]{0.4, 0, 0.6}P\color[rgb]{0.5, 0, 0.5}R\color[rgb]{0.5, 0, 0.5}O\color[rgb]{0.6, 0, 0.4}B\color[rgb]{0.6, 0, 0.4}A\color[rgb]{0.6, 0, 0.4}B\color[rgb]{0.7, 0, 0.3}L\color[rgb]{0.7, 0, 0.3}Y\color[rgb]{0.8, 0, 0.2} \color[rgb]{0.8, 0, 0.2}B\color[rgb]{0.8, 0, 0.2}O\color[rgb]{0.9, 0, 0.1}R\color[rgb]{0.9, 0, 0.1}K\color[rgb]{1.0, 0, 0.0}E\color[rgb]{1.0, 0, 0.0}N}$ 🎵

[![image](https://github.com/user-attachments/assets/311bc0cf-f09f-4cf5-9085-86368b9dccbf)](https://www.youtube.com/watch?v=hakrt4XFzbg)

**Comment by numfin** [comment]
tempting to press 

<img width="129" height="59" alt="Image" src="https://github.com/user-attachments/assets/4c7315e7-30ea-4ef5-98b3-61eff3b2642d" />

**Comment by Dunravin** [comment]
Why do you want to sound like another person and augment their mood state? Creepy.
