### ISSUE TITLE
[UX] Hide toolbar navigators when settings menu is open

### ISSUE THREAD

**Issue by B-E-A-F** [overlayeddev/overlayed#18]
![image](https://github.com/Hacksore/overlayed/assets/20789620/aad74d5c-a765-4307-9905-5e561d907b0c)

Steps to reproduce:
1. Click on the settings
2. Be able to make other changes via the toolbar
3. Be confused because there are no visible changes

Possible solutions:
- Hide the toolbar buttons when you are in the settings menu
- Remove exit settings button, make settings a toggle button, hide the toolbar buttons
  - Maybe make the Overlayed icon navigate you back to home (the list of displayable users)

**Comment by Hacksore** [comment]
This was fixed in #20 and will likely ship in `v0.3.0`.
