### ISSUE TITLE
Support for modded Discord

### ISSUE THREAD

**Issue by Heus-Sueh** [overlayeddev/overlayed#185]
Is it possible to provide support for modified discords like [ArmCord](https://github.com/ArmCord/ArmCord)?

**Comment by Hacksore** [comment]
Hey thanks for the issue. Pretty much the same thing for ArmCord as Vesktop and others who use OpenAsar/arrpc.

Currently we are blocked by this issue 👉 https://github.com/OpenAsar/arrpc/issues/18

Tagging this for ref as well.
https://github.com/ArmCord/ArmCord/issues/552

Closing this for now but if it ever gets patched in OpenAsar/arrpc we can revisit this.
