### ISSUE TITLE
Overlayed does not display in the game

### ISSUE THREAD

**Issue by RutsuKun** [overlayeddev/overlayed#189]
**Describe the bug**
When I have the Nier Automata game running, Overlayed is not visible in the game.

**To Reproduce**
1. Open Overlayed
2. Run game
4. See issue

**Expected behavior**
Would like to see overlayed in the game

**Screenshots**
![image](https://github.com/user-attachments/assets/b7c16284-925a-47e3-b015-d42b6e4907a2)
![image](https://github.com/user-attachments/assets/6677fa58-72a7-43a5-9659-d5e06470f004)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 23H2

**Comment by Hacksore** [comment]
@RutsuKun can you check the game supports [borderless fullscreen windowed](https://www.pcgamingwiki.com/wiki/Glossary:Windowed#Borderless_fullscreen_windowed) mode?

https://overlayed.dev/blog/discord-overlay-in-any-game

**Comment by RutsuKun** [comment]
Works
![image](https://github.com/user-attachments/assets/901e2555-cd77-489b-b9f6-f6da22658000)
