### ISSUE TITLE
Customizable Overlay

### ISSUE THREAD

**Issue by Exohayvan** [overlayeddev/overlayed#193]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
Would love to be able to change the size of the usernames, profile pictures or even add a slight outline/background to the overlay.

**Describe alternatives you've considered**
I've checked out [Remedy](https://github.com/Naozumi520/Remedy) unfortunately only works on a couple of my Macs.

**Additional context**
Something like this (Pulled from Remedy):
![260094472-a38f783b-01bb-4762-a73b-aee93639341e](https://github.com/user-attachments/assets/bfc8e9d6-d1e0-44ba-949f-b7a9458bab66)

**Comment by Exohayvan** [comment]
Existing issue that's in the same realm: https://github.com/overlayeddev/overlayed/issues/74

**Comment by Hacksore** [comment]
Yeah it's def planned with #74, not sure when I can get around to it though. 

If anyone is willing to take a stab with a PR I'd appreciate it 🙏.

Let's move the discussion there, closing this one
