### ISSUE TITLE
Doesn't work on Red Star OS

### ISSUE THREAD

**Issue by JoshHyde9** [overlayeddev/overlayed#198]
**Shit's broken**
https://en.wikipedia.org/wiki/Red_Star_OS

**Comment by PickleNik** [comment]
> **Shit's broken** https://en.wikipedia.org/wiki/Red_Star_OS

# works on my machine
![image](https://github.com/user-attachments/assets/982af205-dd27-447b-8d15-10bf1519843d)

**Comment by Hacksore** [comment]
i dont use linux so im sorry for you
