### ISSUE TITLE
Doesnt work on wm :)

### ISSUE THREAD

**Issue by adityadafe** [overlayeddev/overlayed#2]
![image](https://github.com/Hacksore/overlayed/assets/97914006/4025e280-d82c-4c12-b44c-605e073d3e5d)

i use arch btw

**Comment by Hacksore** [comment]
closed `wontfix` because you use arch btw.

**Comment by WalterWoshid** [comment]
@Hacksore ???

**Comment by Hacksore** [comment]
What in the arch Linux is going on here?
