### ISSUE TITLE
window doesnt go away when expanded

### ISSUE THREAD

**Issue by pollux78** [overlayeddev/overlayed#205]
**Describe the bug**
window outline doesnt go away when you fullscreen overlayed

**To Reproduce**
1. open overlayed on linux, fullscreen it and pin it
2. you'll notice the window outline before expanding is still there when expanded

**Expected behavior**
for that outlined window to not be there

**Screenshots**
![image](https://github.com/user-attachments/assets/2b41e585-da17-4fa7-995a-a1254e2a201f)

**Desktop (please complete the following information):**
 - OS: arch linux
 - Version 0.5.0

**Additional context**

**Comment by Hacksore** [comment]
hmm maybe this is a tauri bug? How did you install the app?

**Comment by pollux78** [comment]
> hmm maybe this is a tauri bug? How did you install the app?

Through appimage

**Comment by Hacksore** [comment]
@LucFauvel can you help us troubleshoot this pretty please ❤️
