### ISSUE TITLE
Add support for Vesktop/other clients

### ISSUE THREAD

**Issue by imnottimaq** [overlayeddev/overlayed#209]
It would be nice to see it, because for me auth is not working in vesktop

**Comment by Hacksore** [comment]
vesktop is not supported see the following issue https://github.com/overlayeddev/overlayed/issues/78

maybe one day that will change 🙏

**Comment by imnottimaq** [comment]
> vesktop is not supported see the following issue #78
> 
> maybe one day that will change 🙏

understood
