### ISSUE TITLE
Fix maximize crash on mac

### ISSUE THREAD

**Issue by Hacksore** [overlayeddev/overlayed#211]
Since nspanels can't be maximized it's crashing at runtime when double clicking the `main` fake titlebar on mac.

setup a repro for this and @ahkohd can hopefully help figure out the root cause.
https://github.com/Hacksore/ns-panel-tauri-v2-maximize-bug

**Comment by Hacksore** [comment]
This seems to have fixed it in the repro https://github.com/Hacksore/ns-panel-tauri-v2-maximize-bug/commit/8f87a50fe392f37e1301ed6f842c93d9b669a162 will make a patch here.

**Comment by Hacksore** [comment]
@ahkohd so this does prevent the crash but now you can't resize the window 😂.

```diff
From dbe7df81e691a051ecc690019409dbfd80140a87 Mon Sep 17 00:00:00 2001
From: Sean Boult <996134+Hacksore@users.noreply.github.com>
Date: Fri, 13 Sep 2024 07:44:44 -0500
Subject: [PATCH] Prevents crash but you can't resize

---
 apps/desktop/src-tauri/src/window_custom.rs | 5 +----
 1 file changed, 1 insertion(+), 4 deletions(-)

diff --git a/apps/desktop/src-tauri/src/window_custom.rs b/apps/desktop/src-tauri/src/window_custom.rs
index fc5b47b..bba343e 100644
--- a/apps/desktop/src-tauri/src/window_custom.rs
+++ b/apps/desktop/src-tauri/src/window_custom.rs
@@ -31,10 +31,7 @@ pub mod macos {
       #[allow(non_upper_case_globals)]
       const NSWindowStyleMaskNonActivatingPanel: i32 = 1 << 7;
 
-      #[allow(non_upper_case_globals)]
-      const NSResizableWindowMask: i32 = 1 << 3;
-
-      panel.set_style_mask(NSWindowStyleMaskNonActivatingPanel + NSResizableWindowMask);
+      panel.set_style_mask(NSWindowStyleMaskNonActivatingPanel);
 
       panel.set_collection_behaviour(
         NSWindowCollectionBehavior::NSWindowCollectionBehaviorCanJoinAllSpaces
-- 
2.46.0
```

**Comment by ahkohd** [comment]
Add the  the resizable style mask:

```
 #[allow(non_upper_case_globals)]
const NSResizableWindowMask: i32 = 1 << 3;

panel.set_style_mask(NSWindowStyleMaskNonActivatingPanel + NSResizableWindowMask);
```

**Comment by Hacksore** [comment]
@ahkohd i think you are misunderstanding this. `NSResizableWindowMask` is what is causing the crash because it's allowing double click to attempt maximize.

**Comment by ahkohd** [comment]
i see.

**Comment by ahkohd** [comment]
https://github.com/user-attachments/assets/e6be6c57-947d-474e-9c36-8b37da9aadf0

strange, Menote editor panel does not crash with the resize style mask

**Comment by ahkohd** [comment]
<img width="1332" alt="image" src="https://github.com/user-attachments/assets/403f39eb-8d3a-4383-9a34-7a106120ce32">
<img width="1332" alt="image" src="https://github.com/user-attachments/assets/de94d255-64fc-4030-8047-217e5b304278">
<img width="1332" alt="image" src="https://github.com/user-attachments/assets/4e44ad58-ae71-4394-9c05-081e669f3fcd">

**Comment by Hacksore** [comment]
I've updated the repro to use the same flags that are crashing Overlayed https://github.com/Hacksore/ns-panel-tauri-v2-maximize-bug.


@ahkohd are you using `data-tauri-drag-region` at all because that's how im making the "fake header" allowing you to move the panel.

**Comment by ahkohd** [comment]
> I've updated the repro to use the same flags that are crashing Overlayed https://github.com/Hacksore/ns-panel-tauri-v2-maximize-bug.
> 
> @ahkohd are you using `data-tauri-drag-region` at all because that's how im making the "fake header" allowing you to move the panel.

yes I am.

**Comment by Hacksore** [comment]
@ahkohd thanks for looking into this, got a simple patch in https://github.com/overlayeddev/overlayed/commit/93d9a661942c69419a34a8255d67840944fdb8f9
