### ISSUE TITLE
v0.6.0 Settings window can't be closed

### ISSUE THREAD

**Issue by buddhapest** [overlayeddev/overlayed#215]
**Describe the bug**
Settings window can't be closed

**To Reproduce**
Press gear for settings, press X to close settings.  Window stays open and there is no way to get rid of it

**Expected behavior**
Some way of closing the settings dialog

**Desktop (please complete the following information):**
 - OS: Windows 10.0.22631 x86_64
 - Tauri 2.0.0-rc8
 - App 0.6.0

![image](https://github.com/user-attachments/assets/54cb4dc0-6b84-4a6a-80dc-663d587924da)

**Comment by Hacksore** [comment]
Yeah I'd fixed canary but will get a patch version out shortly.

**Comment by Hacksore** [comment]
Published `v0.6.1` and it should be available for auto update.

**Comment by buddhapest** [comment]
verified, thank you
