### ISSUE TITLE
Allow clickthrough under heading bar

### ISSUE THREAD

**Issue by buddhapest** [overlayeddev/overlayed#216]
**Is your feature request related to a problem? Please describe.**

It's very frustrating to try and click on a window that Overlayed overlaps and realizing that you have to move the invisible window that Overlayed generates.

![image](https://github.com/user-attachments/assets/98c09183-870b-4101-b59c-92b976415211)

**Describe the solution you'd like**

Option for the "overlay" area to be clickthrough so that you can click on stuff behind the window.  This is especially important when you have "Only show users who are speaking".

**Describe alternatives you've considered**

Another option would be to draw a border and transparency in the overlay area but that makes it less of an overlay ;)

**Comment by buddhapest** [comment]
looks like someone's got a PR just for that: https://github.com/overlayeddev/overlayed/pull/169

just needs to be fixed

**Comment by Hacksore** [comment]
Yeah this one is hard to solve properly cause we want the transparent window.

A long time ago I had a hover color when you put your mouse over the window but on macOS it's really lame cause it only works if the window is focused.

#169 is slightly different as that for pinned mode and "seeing what's behind" when you mouse over, and it's royal borked in windows.

I just played with a border which I kind of like cause you really should not be using Overlayed unless you pin it.

The border gives you idea of where it's blocking as well as helping you resize it when you need to.

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/66ff3e07-b987-4ae7-9395-7935902214b6">

**Comment by Hacksore** [comment]
Here is a quick demo of what can help but not fix it fully.

https://github.com/user-attachments/assets/57a774c8-d727-4f89-8ac4-60475947f12c

**Comment by buddhapest** [comment]
cool, thank you @Hacksore

**Comment by Hacksore** [comment]
I think with the new boarder this is better, not fully solved, but if anyone has good ideas on how to make the UX better PRs are welcome 🙏.
