### ISSUE TITLE
App not installing correctly, freezing on opening of settings

### ISSUE THREAD

**Issue by magsa88** [overlayeddev/overlayed#219]
**Describe the bug**

Tried to install several times. It doesn't open a screen when I first click on the thumbnail, it just puts your logo in my upper right bar. When I click on the logo, nothing happens. 'Show overlayed' nothing happens same for 'reload overlayed'. 'open devtools' works, but only certain tabs. I cannot access 'storage', 'sources', 'network' or 'timelines'. When I try 'open devtools (settings window) that works, but again, limited movement within the screen. When i open 'settings' the only thing I can do is tick 'only show users who are speaking' i cannot open devtools, config directory, i can't even click where you have 'found a bug' clickable portion. 

It also makes my other open apps unclickable when it is 'open' (as in, in the top right hand corner) even when clicked onto this screen I am writing this report in. I had to close the app to be able to continue typing. 

I have had overlayed installed before and never had this issue. I cannot find residual files anywhere so I am stumped. 

**To Reproduce**

**Expected behavior**

I expected an install screen as shown on 'how to install', this didn't happen, it just went to the upper right shortcut bar and gave me no screen. I deleted it and tried to reinstall using the brew method, which did a full install and put it into my applications, but left me with the same issues upon opening. 

**Screenshots**

<img width="1675" alt="Screenshot 2024-09-21 at 20 23 39" src="https://github.com/user-attachments/assets/0bf8682c-7355-4442-b54e-47678825dfb8">
<img width="1022" alt="Screenshot 2024-09-21 at 20 23 48" src="https://github.com/user-attachments/assets/acb87a86-c431-4c0c-87fd-860466520115">
<img width="1032" alt="Screenshot 2024-09-21 at 20 23 58" src="https://github.com/user-attachments/assets/580b4f56-73af-4687-ae11-59aa5894d742">
<img width="1035" alt="Screenshot 2024-09-21 at 20 24 46" src="https://github.com/user-attachments/assets/1b4dc57d-a283-4b3c-bd40-4d270f485b8e">
<img width="996" alt="Screenshot 2024-09-21 at 20 25 04" src="https://github.com/user-attachments/assets/3bf5622e-4324-4db2-a7ea-b480ee8ffb52">
<img width="1047" alt="Screenshot 2024-09-21 at 20 25 18" src="https://github.com/user-attachments/assets/13bae0f8-8f91-41d4-a4a3-1904840c2bb3">
<img width="1031" alt="Screenshot 2024-09-21 at 20 25 28" src="https://github.com/user-attachments/assets/01ea5038-d5d1-4a66-9d50-ce0b4badcafe">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] intel quad core i7 Ventura 13.7 - Intel Iris Plus Graphics 645 1536 MB (running ventura due to issues with latest OS updates not intended for intel based macs).
 - Version [e.g. 22] 0.6.1

Happy to provide any other metrics you need from my system. 

**Additional context**

First attempted install I was in a call on discord, this did not lead to main functionality of overlayed appearing, it did nothing except what I've described. Thanks for any help!

**Comment by Hacksore** [comment]
Hi @magsa88, thanks for reporting the issue I appreciate it!

Once the canary build is released can you give it a try? It has two fixes that should help here.

- Add a polyfill for `Promise.withResolvers` https://github.com/overlayeddev/overlayed/commit/a0483fe3582adff0608883b9a51c4b1d1461f7db
- Subscribe to `VOICE_CHANNEL_SELECT` events https://github.com/overlayeddev/overlayed/commit/7f061cd8820b2e6a7279258ee6a2fc10a01e8ebe

It is running now here:
https://github.com/overlayeddev/overlayed/actions/runs/10975919454

once it's done you should be able to get it here:
https://overlayed.dev/canary

Once we confirm this is working I can do another quick patch release 🙏

**Comment by magsa88** [comment]
Of course, thanks so much for the quick response! Please let me know when it's live or if you want me to test it in Beta :)

**Comment by magsa88** [comment]
So it is to do with me having to run Ventura? You may find that more common now they are moving away from Intel support, so I appreciate the fixes!

**Comment by Hacksore** [comment]
@magsa88 yeah it was the older OS for one of the bugs and there was a new bug with channels im not sure why it popped up 😫.

You can download canary (beta version) from here now.
https://overlayed.dev/canary

Since this one is not signed by apple you'll have to right click open the first time.

<img width="466" alt="image" src="https://github.com/user-attachments/assets/ce63536f-a814-4dba-9b2f-574a5d87f399">

**Comment by magsa88** [comment]
It's coming down in document format, not DMG 🫣

**Comment by Hacksore** [comment]
Oh that's my bad! the file does not have `.zip` but if you add it you can extract it.

Let me get a fix for that!

**Comment by magsa88** [comment]
Working perfect! thank you!

**Comment by Hacksore** [comment]
Awesome, I'll get version `v0.6.2` out shortly 🫡

**Comment by magsa88** [comment]
Not sure if this was intended, but was just logging off and spotted this, so thought i'd let you know! (checked in a diff browser too, to be sure!) Doesn't affect me now as the app is working like a dream! But just incase it's not intentional, thought you'd wanna know!

Thanks again for getting a resolution done to the issue soooo quick!

<img width="776" alt="Screenshot 2024-09-22 at 00 26 34" src="https://github.com/user-attachments/assets/b683297a-a950-4308-8caa-87d876d2bb76">

**Comment by Hacksore** [comment]
I just pushed a fix for that 😂
