### ISSUE TITLE
slowly fading names

### ISSUE THREAD

**Issue by buddhapest** [overlayeddev/overlayed#223]
**Is your feature request related to a problem? Please describe.**
I use Overlayed with OpenKneeboard in VR (and it's amazing like that).  But I have to turn my head in order to see who is talking and if they just finished then their name is no longer lit up.

**Describe the solution you'd like**
Ability to set a time to fade the name after someone stops speaking so you can tell for 1 or 2 seconds longer after they stopped.

**Describe alternatives you've considered**
Turning my head faster :)

**Comment by Hacksore** [comment]
I tried playing with this one but not sure how to make it work well. I played around with CSS animations with tailwind but didn't find a solution that gave a good UX.

Perhaps if anyone has ideas on the tech side of things here please do share.

**Comment by Hacksore** [comment]
It was hard for me to figure out an impl for this but I will still accept any PRs that pull it off

Closing issue for now so we can keep highest priority ones open.
