### ISSUE TITLE
platform install links no worky

### ISSUE THREAD

**Issue by PatrickJS** [overlayeddev/overlayed#26]
I can't install something 

<img width="1037" alt="Screenshot 2024-01-05 at 1 54 50 PM" src="https://github.com/Hacksore/overlayed/assets/1016365/09f07391-eb8a-4f77-9b2a-66ba5d038490">

**Comment by niemal** [comment]
I plead guilty and it is fixed. :)

**Comment by PatrickJS** [comment]
I think you need QA
![image](https://github.com/Hacksore/overlayed/assets/1016365/e73cbde8-538d-43c9-826b-fbf4082774ec)


is this VC funded?

(voice chat funded 😏)

**Comment by Hacksore** [comment]
🫡
