### ISSUE TITLE
Incomplete Onboarding

### ISSUE THREAD

**Issue by danstepanov** [overlayeddev/overlayed#29]
`rustc --version`
```
rustc 1.75.0 (82e1608df 2023-12-21)
```

`pnpm --version`
```
8.9.2
```

`node --version`
```
v20.10.0
```

pnpm start --filter=desktop
```
 Compiling tauri-plugin-window-state v0.1.0 (https://github.com/tauri-apps/plugins-workspace?branch=v1#ba6acafb)
desktop:start:    Compiling tauri-plugin-websocket v0.0.0 (https://github.com/tauri-apps/plugins-workspace?branch=v1#ba6acafb)
    Finished dev [unoptimized + debuginfo] target(s) in 45.88s
```

Now Overlayed is open on my desktop but nothing is happening.
<img width="166" alt="Screenshot 2024-01-07 at 8 06 57 PM" src="https://github.com/Hacksore/overlayed/assets/5482800/a2be5041-a510-4df3-a0d3-6b3afe7c2fd2">

Apple M2 Max
Sonoma 14.1.2

**Comment by Hacksore** [comment]
few things to verify/try.

- is your discord open
- are you connected to a voice chat
- can you try selecting Overlayed from the menu bar -> show overlayed

Expected behavior should be a window spawns with a custom title bar.

**Comment by Hacksore** [comment]
@danstepanov if this comes back crank a new issue out otherwise find me in the discord.
