### ISSUE TITLE
[marketing] need good looking header

### ISSUE THREAD

**Issue by Hacksore** [overlayeddev/overlayed#3]
something like this
![image](https://github.com/Hacksore/overlayed/assets/996134/6a4ecef4-aa22-44ca-b3ea-69ea205fee1e) (https://www.spacedrive.com/)

**Comment by maxdemaio** [comment]
I shall cook *(unless)*

![](https://media1.tenor.com/m/aoPWAAKvid0AAAAC/batman-thinking.gif)
