### ISSUE TITLE
Add option to only show who is speaking

### ISSUE THREAD

**Issue by paschi** [overlayeddev/overlayed#46]
It would be nice to have an option to only show who is currently speaking instead of always the full list of all channel members. I'm often in channels with 20+ people and it is difficult to find out who is speaking with the full list of members. Also it clutters the screen.

**Comment by Hacksore** [comment]
Working on this as it's good idea, thanks for the request. 

Quick rough draft demo

https://github.com/Hacksore/overlayed/assets/996134/e8673e60-4def-41e3-9c23-eca02d8d42cc

**Comment by emiltoacs** [comment]
Hi thanks for working on this feature. 
IMO it would be more readable to add a delay to let the speaker visible a few seconds after he stopped speaking. That would avoid some blinking pseudo, and the time to read and visualize the picture for people just saying quick answer as yes or no.

**Comment by Hacksore** [comment]
@emiltoacs not a bad idea but probably best to ship the current approach first then figure out how to add delay.

**Comment by Hacksore** [comment]
Implemented via #47 and will be part of the next release.

**Comment by paschi** [comment]
Thanks for implementing this! Any idea when this will get released? Looking forward to having this feature. 😄

**Comment by Hacksore** [comment]
No ETA as I'd like to see if I can ship the "official allowlisting" from Discord but that is sorta stalled ATM.

If you ever want to live on the edge you can always run the canary build to get this feature now.

I guess I should make a blog post on how to consume the canary build for others 😅.

https://github.com/Hacksore/overlayed/actions/runs/8428739388 (unstable build at the bottom of this)

**Comment by paschi** [comment]
I tried out the nightly build yesterday on my Mac and unfortunately it doesn't seem to be working. Both the main window and the settings window are empty. For the settings windows I at least see the title bar, but not more. When I open the devtools for the settings window there is an error `Error: Missing Axiom token`. Don't know if this is the root cause. Should I create a separate ticket for this issue? If you don't want to fix this now I will just wait for the next release.

**Comment by Hacksore** [comment]
@paschi Oh no I forgot to include the `VITE_AXIOM_TOKEN`, the next nightly should be fixed with 0599ff895ce8a4b4e19b3054775018bfa9f3b64a.

Kicking off the job now to generate a new nightly version.
https://github.com/Hacksore/overlayed/actions/runs/8475115732

**Comment by paschi** [comment]
I tried the new nightly build and it's working great. Thanks!

**Comment by stvsu** [comment]
Would love to see a delay config option to add a (small) delay to any speaker so they stay highlighted after finishing speaking
