### ISSUE TITLE
[marketing] good looking scrollbars

### ISSUE THREAD

**Issue by Hacksore** [overlayeddev/overlayed#5]
They should be dark mode

![image](https://github.com/Hacksore/overlayed/assets/996134/fe494c5e-e588-483e-8e57-51568b5daf6b)

**Comment by MVAodhan** [comment]
hi, is this taken?

**Comment by Hacksore** [comment]
> hi, is this taken?

no, :shipit: my dud

**Comment by MVAodhan** [comment]
#7 I think it looks clean
![image](https://github.com/Hacksore/overlayed/assets/69143973/36ca3b81-e92d-4e3b-ba47-8a8274e3e0b5)

**Comment by Hacksore** [comment]
Fixed in #7
