### ISSUE TITLE
UI Nav bar

### ISSUE THREAD

**Issue by Hacksore** [overlayeddev/overlayed#53]
make nav bar like this with links
![image](https://github.com/Hacksore/overlayed/assets/996134/2b68d19b-b4b2-4152-8a94-6900ddcecf5b)

- Home
- About
- Blog

**Comment by maxdemaio** [comment]
i like turtles

**Comment by Hacksore** [comment]
make a burger too 
![image](https://github.com/Hacksore/overlayed/assets/996134/8148456e-2a55-4a11-bd8c-49dddb16bfaa)

**Comment by maxdemaio** [comment]
frick you, I'll start on this now

**Comment by Hacksore** [comment]
Fixed via #59
