### ISSUE TITLE
Can't have the popup in all workspace or fellow you 

### ISSUE THREAD

**Issue by abdelhadia72** [overlayeddev/overlayed#55]
Can't have the popup in all workspace or fellow you I can see it only in one window ?

**Comment by Hacksore** [comment]
So for macOS it's enabled to show on all workspaces with a custom tweak. Are you on linux or windows by chance?

https://github.com/Hacksore/overlayed/blob/1b5a8ae81e8c4d7c7b3d2b8b192858402cf071e6/apps/desktop/src-tauri/src/main.rs#L40

https://github.com/Hacksore/overlayed/blob/12347be8385c99e52def78ce080107d1ae7c1154/apps/desktop/src-tauri/src/window_custom.rs#L25-L41

**Comment by Hacksore** [comment]
This was closed accidentally but if you can provide more info we can try to solve this.
