### ISSUE TITLE
[marketing] fix footer on mobile

### ISSUE THREAD

**Issue by Hacksore** [overlayeddev/overlayed#6]
Needs to be centered 

![image](https://github.com/Hacksore/overlayed/assets/996134/0423f25d-d6b4-40cb-8432-f7b4c64cba28)

**Comment by maxdemaio** [comment]
I can pick this up

![](https://media.discordapp.net/attachments/837800765602005051/1179092223338492094/5caedf9af25b18e42a09654f2d7d0a50c97bcd36.gif?ex=658afb34&is=65788634&hm=2fee5b8fa487f9e0356adbb70464b3ae05f1e3149ef61630d642b762b5b68263&=&width=800&height=538)
