### ISSUE TITLE
Vertical layout for avatar only mode

### ISSUE THREAD

**Issue by DevNim98** [overlayeddev/overlayed#69]
It would be nice to allow vertical layout when showing only avatars.

**Comment by Hacksore** [comment]
I think you can workaround this by squishing the window.

https://github.com/Hacksore/overlayed/assets/996134/805a7662-ad93-4158-93f6-902e50d5724b

**Comment by Hacksore** [comment]
but perhaps in the future we can add a standalone layout for this so you don't have to do this.
