### ISSUE TITLE
Random lags in game

### ISSUE THREAD

**Issue by zenitogr** [overlayeddev/overlayed#71]
game dota 2

I get random lags

when exiting overlayed the random lags stop

how to solve this?

**Comment by zenitogr** [comment]
is any of your code not async?

**Comment by zenitogr** [comment]
lots of errors in dev console

**Comment by zenitogr** [comment]
fresh start of overlayd 
![image](https://github.com/Hacksore/overlayed/assets/109196423/d7c8d909-3248-476c-b0bc-f7e9fb0d0bd6)

**Comment by Hacksore** [comment]
Some questions

- what operating system?
- are you using with fullscreen borderless windowed?
- does it happen in other games?

**Comment by zenitogr** [comment]
Windows 11
Borderless windowed
Only play dota 2

**Comment by zenitogr** [comment]
I now play euro truckk simulator 2 and BeamNG.drive and AOE 2 

I will test with all the games

stand by

**Comment by zenitogr** [comment]
I report no random lags in Dota 2 today, I guess something was faulty before in my windows installation!

ok! closing!
