### ISSUE TITLE
Windows & Linux One Line Installers

### ISSUE THREAD

**Issue by SticksDev** [overlayeddev/overlayed#72]
An installer script for Linux and Windows would be excellent, and I would be willing to add them. It's pretty simple to make them nowadays, and you can make a simple Cloudflare worker to handle sending the correct script to the user. Here's how I thought about implementing it:

Because Windows is a .msi, you can use [`msiexec`](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/msiexec) to install the msi within a PowerShell script. It's pretty simple to get the latest version using the GitHub API.

For Linux, .debs can be installed using `dkpg -i`; the only caveat is that `dkpg` must be run as root. 

There's no use for Mac as Homebrew already has a package for overlayed package.

Let me know what you think

**Comment by Hacksore** [comment]
Can you link examples of how other popular tools do this? [Rust](https://rustup.rs) seems to just give you the exe to download/run.

I'd imagine it'd be something like this for windows but wanna see what the vibe is.

```
powershell -command "& {Invoke-WebRequest -Uri '<CDN_URL>' -OutFile 'installer.exe'}; Start-Process 'installer.exe' -Wait; Remove-Item 'installer.exe'" 
```

**Comment by Hacksore** [comment]
Also FWIW, you can find the latest download bins here, so this might help when scripting it.

https://api.overlayed.dev/latest

**Comment by Hacksore** [comment]
You can send a PR for this if you have a good lookin™ command for winderz.

Closing the issue for now though!

**Comment by Hacksore** [comment]
Here is a bun tweet and they do https://x.com/bunjavascript/status/1796856115877359694?s=46&t=wcJWAj_mdr7mNg_eOgQdPA

```
powershell -c "irm bun.sh/install.ps1 | iex"
```
