### ISSUE TITLE
Overlay size settings

### ISSUE THREAD

**Issue by Pegazse** [overlayeddev/overlayed#74]
Hello i can't find the setting to change the overlay size it take so much space on my 15in screen.

**Comment by Hacksore** [comment]
Definitely a needed feature but requires a bit of thought.

One way could be simply allowing zoom if it’s not horribly scuffed. Otherwise I’ll have to do it all via css/js.

https://github.com/tauri-apps/tauri/issues/3310

**Comment by Hacksore** [comment]
@exohayvan also I forget I have this PR up https://github.com/overlayeddev/overlayed/pull/162

😂
