### ISSUE TITLE
User roles text colors

### ISSUE THREAD

**Issue by reikolydia** [overlayeddev/overlayed#75]
Right now the text is white on a grey background, perhaps we could customize the colors? Like role colors from vencord plugin "RoleColorEverywhere" - voice users

**Comment by Hacksore** [comment]
Unfortunately I don’t think I can pull this off based on the API limitations.

If you can think of any way to make this possible please do suggest how it could work.

Going to close this for now but if we find a way I can reopen it.

https://discord.com/developers/docs/topics/rpc#voicestatecreatevoicestateupdatevoicestatedelete-example-voice-state-dispatch-payload
