### ISSUE TITLE
Overlay doesn't work on fullscreen windows

### ISSUE THREAD

**Issue by Devanshul05** [overlayeddev/overlayed#80]
I would love to have this feature if possible. I tried working around it, but i couldn't do it. Is there a workaround for it? Thanks

**Comment by Hacksore** [comment]
Going to start a blog post that will describe how you can enable "Borderless Windowed Mode" which should work for most games.

**Comment by Hacksore** [comment]
Blog is up https://overlayed.dev/blog/discord-overlay-in-any-game
